//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborCosts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int Id { get; set; }
        public string Fio { get; set; }
        public string Phone { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
