//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborCosts
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborCosts
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int HourCount { get; set; }
        public int Total { get; set; }
        public int IdProject { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
